apiVersion: v2
name: metoro-exporter
description: A helm chart for the Metoro Exporter

type: application

version: 0.455.0
appVersion: 0.432.0

dependencies:
  - name: opentelemetry-operator
    version: 0.69.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: otelInstrumentation.enabled
  - name: redis
    version: 20.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled