apiVersion: v2
name: metoro-exporter
description: A helm chart for the Metoro Exporter

type: application

version: 0.450.0
appVersion: 0.432.0

dependencies:
  - name: prometheus
    version: 25.27.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: clickhouse
    version: 6.2.23
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: opentelemetry-operator
    version: 0.69.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: otelInstrumentation.enabled
