{{- if .Values.exporter.autoscaling.horizontalPodAutoscaler.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.exporter.metadata.name}}
  minReplicas: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.minReplicas}}
  maxReplicas: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.maxReplicas}}
  targetCPUUtilizationPercentage: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.targetCPUUtilizationPercentage}}
{{- end -}}