{{- if .Values.exporter.autoscaling.horizontalPodAutoscaler.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.exporter.metadata.name}}
  minReplicas: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.minReplicas}}
  maxReplicas: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.maxReplicas}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.exporter.autoscaling.horizontalPodAutoscaler.targetCPUUtilizationPercentage}}
{{- end -}}