# If the externalSecret is enabled, we will not create our own secret, instead we will reference the external secret
{{ if not .Values.exporter.secret.externalSecret.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exporter.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AUTH_TOKEN: {{ .Values.exporter.secret.bearerToken | b64enc | quote }}
{{ end }}