{{ if .Values.otelInstrumentation.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.instrumentationWebhook.name}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metoro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.instrumentationWebhook.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: metoro-instrumentation-webhook
  template:
    metadata:
      {{- with .Values.instrumentationWebhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: metoro-instrumentation-webhook
    spec:
      serviceAccountName: {{ .Values.instrumentationWebhook.serviceAccount.name }}
      volumes:
        - name: webhook-cert
          secret:
            secretName: {{ .Values.instrumentationWebhook.secretName }}
      containers:
        - name: {{ .Values.instrumentationWebhook.name }}
          image: "{{ .Values.instrumentationWebhook.image.repository }}:{{ .Values.instrumentationWebhook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.instrumentationWebhook.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-cert
              readOnly: true
          env:
            - name: VERSION
              value: {{ .Chart.AppVersion }}
            - name: GIN_MODE
              value: release
          resources:
            {{- toYaml .Values.instrumentationWebhook.resources | nindent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - metoro-instrumentation-webhook
{{- end -}}