{{- if .Values.otelInstrumentation.enabled -}}
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: metoro-otel
  namespace: metoro
spec:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlphttp:
        endpoint: {{ printf "http://%s.%s.svc.cluster.local:%d" .Values.clusterServer.services.openTelemetryCollector.metadata.name .Release.Namespace (.Values.clusterServer.services.openTelemetryCollector.ports.otel.port | int) }}
        tls:
          insecure: true
      debug: {}

    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp, debug]
{{- end -}}