{{ if .Values.otelInstrumentation.enabled}}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  namespace: python-microservices
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://metoro-otel-collector.metoro.svc.cluster.local:4317
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://metoro-otel-collector.metoro.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_EXPORTER_OTLP_TRACES_PROTOCOL
        value: http/protobuf
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_EXPORTER_OTLP_METRICS_PROTOCOL
        value: http/protobuf
  dotnet:
    env:
      # Required if endpoint is set to 4317.
      # dotnet autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      # - name: OTEL_EXPORTER_OTLP_ENDPOINT
      #  value: http://metoro-otel-collector.metoro.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
  go:
    env:
      # Required if endpoint is set to 4317.
      # Go autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://metoro-otel-collector.metoro.svc.cluster.local:4318
      #- name: OTEL_EXPORTER_OTLP_PROTOCOL
      #  value: grpc
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
  java:
    env:
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
{{- end -}}